version: '3.7'
services:
    server:
        env_file: "./backend/.env"
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        image: "server"
        ports:
            - "3000:3000"
    client:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        image: "client"
        ports:
            - "8080:8080"
        links:
            - "server"